### ISSUE TITLE
Prepare for Release

### ISSUE THREAD

**Issue by BenGalewsky** [ritwik-deshpande/CustomImageBuilder#1]
Here are some things that need to be cleaned up for us to be able to announce this library

- [x] Clean up the dependencies to just be globus-compute-sdk
- [x] Remove references to "Delta" in the comments. This library works on all endpoints
- [x] Add type hints to the function arguments
- [x] Remove `echo "----- Demo Image ----------"` from the jinja template
- [x] Allow users to pass in their own GlobusComputeClient
- [x] Remove the commented out `__main__` from the end of image_builder.py 
- [x] Move README to root directory (not down in the `custom_image_builder` subdirectory
- [x] Remove `__pycache__` from the exception package
- [x] Create a .gitignore for python projects
- [x] Remove the `config.yaml` from the example 
- [x] Add a line to the example that shows how you actually invoke a function in the newly built container

**Comment by ritwik-deshpande** [comment]
There is a .gitignore in the repository, where should I add for python projects?

**Comment by BenGalewsky** [comment]
> There is a .gitignore in the repository, where should I add for python projects?

I don't see one. I added one via #2
